source 'https://rubygems.org'

gem 'middleman'
gem 'middleman-autoprefixer'
gem 'slim'
gem 'sass'
gem 'middleman-sprockets'
gem 'middleman-livereload'
# gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
# gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
