// Generated by CoffeeScript 1.3.3

$(document).ready(function() {
  $(window).scroll(function() {
    var scrollPos;
    scrollPos = $(this).scrollTop();
    return $("section").css({
      "background-position": "center " + (-scrollPos / 4) + "px"
    });
  });
  $("img.lazy").show().lazyload({
    failure_limit: 10,
    skip_invisible: false,
    effect: "fadeIn"
  });
  $("#registration").on({
    click: function(e) {
      e.preventDefault();
      return window.open('http://registrano.com/events/rubyconf-taiwan-2012', '_blank');
    }
  });
  return $("#navigation a").on({
    click: function(e) {
      e.preventDefault();
      return $("body").stop().scrollTo($($(this).attr("href")), {
        duration: 1200,
        offset: {
          left: 0,
          top: -0.03 * $(window).height()
        }
      });
    }
  });
});
